" Vundle Config {
    set nocompatible
    filetype off
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()
" // Vundle Config
" Plugin list {
    " Color scheme {
        "Bundle 'chriskempson/base16-vim'
        Bundle 'junegunn/seoul256.vim'
        Bundle 'chriskempson/vim-tomorrow-theme'
        Bundle 'nanotech/jellybeans.vim'
    " // Color scheme
    Bundle 'ap/vim-css-color'
    Bundle 'slj/gundo.vim'
    Bundle 'scroolose/nerdtree'
    Bundle 'scroolose/nerdcommenter'
    Bundle 'majutsushi/tagbar'
    "Bundle 'jlanzarotta/bufexplorer'
    "Bundle 'kchmck/vim-coffee-script'
    Bundle 'tpope/vim-surround'
    Bundle 'tpope/vim-markdown'
    "Bundle 'vim-scripts/vim-auto-save'
    Bundle 'Glench/Vim-Jinja2-Syntax'
    "Bundle 'davidhalter/jedi-vim'
    "Bundle 'bling/vim-bufferline'
    Bundle 'nathanaelkane/vim-indent-guides'
    "Bundle 'valloric/YouCompleteMe'
    Bundle 'groenewege/vim-less'
    "Bundle 'wavded/vim-stylus'
    "Bundle 'digitaltoad/vim-jade'
    Bundle 'editorconfig/editorconfig-vim'

    " Ctrl+P {
        Bundle 'Yggdroot/LeaderF'
        "Bundle 'kien/ctrlp.vim'
    " }
    "Bundle 'tpope/vim-fugitive'
    Bundle 'Raimondi/delimitMate'
    Bundle 'godlygeek/tabular'

    " JS beautify
    "Bundle 'maksimr/vim-jsbeautify'
    "Bundle 'einars/js-beautify'

    " Auto close tag
    Bundle 'tpope/vim-ragtag'

    " Snippet
    Bundle 'tomtom/tlib_vim'
    Bundle 'MarcWeber/vim-addon-mw-utils'
    Bundle 'garbas/vim-snipmate'
        " Optional
    Bundle 'honza/vim-snippets'

    " HTML Emmet
    Bundle 'mattn/emmet-vim'

    " Run inside vim
    "Bundle 'thinca/vim-quickrun'

    " Syntax checking
    "Bundle 'scrooloose/syntastic'

    " Status line
    Bundle 'itchyny/lightline.vim'
        "Bundle 'Lokaltog/powerline', {'rtp':'/powerline/bindings/vim'}
        "Bundle 'bling/vim-airline'

    " Colorpicker
    "Bundle 'abijr/colorpicker'

    " Ember.JS
    "Bundle 'dsawardekar/ember.vim'

    "Bundle 'mustache/vim-mustache-handlebars'
    " endplugins
" } // Plugin list

" Config {
    filetype plugin indent on
    syntax on
    colors Tomorrow-Night
    set autoindent
    set backspace=indent,eol,start  " smart backspace
    set expandtab
    set ignorecase
    set shiftround
    set shiftwidth=4
    set smartcase
    set smarttab
    set softtabstop=4
    set tabstop=4
    set dir=~/.vim_swap
    set backupdir=~/.vim_backup
    set backup
    "set regexpengine=1      " Slow vim
    set laststatus=2        " statusline not shown in single window
    "set mouse=a             " Enable mouse

    " If running on terminal
    "if !has('gui_running')
        "set t_Co=256
    "endif

    " Dont know for what {
        set more
        set number
        set scrolloff=3
		"set showcmd
        "set vb t_vb=
        "set wildmenu
    	set history=1000
    	set nowrap
        "set splitbelow
        "set splitright
    	set foldcolumn=0
    	set foldmethod=indent
    	set foldnestmax=10
    	set nofoldenable
    " } // Dont know for what

    " Auto ch dir
    "set autochdir
    set autoread

    " Autoload vimrc
    au BufWritePost .vimrc so ~/.vimrc

    " Gui {
        "set guifont=Source\ Code\ Pro\ Semibold\ 10
        "set guifont=Menlo\ 10
        set guifont=Consolas\ 10
	    set guioptions-=T  " -toolbar
    	set guioptions-=r  " -right scrollbar
        "set guioptions-=m  " -menubar
    " // Gui

    " Per Filetype setting {
        autocmd Filetype html setlocal ts=2 sts=2 sw=2
	    autocmd Filetype coffee setlocal ts=2 sts=2 sw=2
    	autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
    " } // Per Filetype setting
    "
    " Resize window {
        noremap <c-s-up> <c-w>+
        noremap <c-s-down> <c-w>-
        noremap <c-s-left> <c-w>>
        noremap <c-s-right> <c-w><
    " }

    " PluginConfig {
        " nerdtree {
            let NERDTreeQuitOnOpen=1
        " } / nerdtree
        " tagbar {
    	    let g:tagbar_width=30
	    " } / tagbar
        " autosave {
            "let g:auto_save=0
        " }
        " indent-guides {
            let g:indent_guides_start_level=2
            let g:indent_guides_guide_size=1
            if has("gui_running")
                let g:indent_guides_enable_on_vim_startup=1
            endif

        " }
        " code beautify {
            autocmd FileType javascript nnoremap <buffer> <c-f> :call JsBeautify()<cr>
            autocmd FileType html nnoremap <buffer> <c-f> :call HtmlBeautify()<cr>
            autocmd FileType css nnoremap <buffer> <c-f> :call CSSBeautify()<cr>
            " For range beautify
            autocmd FileType javascript vnoremap <buffer> <c-f> :call RangeJsBeautify()<cr>
            autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
            autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>
        " } // code beautify
        " linting {
            "let g:syntastic_python_checkers = ['pyflakes']
            "let g:syntastic_javascript_checkers = ['jslint']
        " } // linting
    " } // Plugin

    " Key mapping {
        let mapleader=","
	    nnoremap <F2> :NERDTreeToggle<cr>
    	nnoremap <F3> :TagbarToggle<cr>
    	nnoremap <F4> :GundoToggle<cr>
	    " Copy paste system clipboard {
	        noremap <C-c> "+y
    	    inoremap <C-v> <Esc>"+gPa
    	    noremap <C-v> "+gP
	    " } / Copy paste system clipboard
        "
    	" Toggle Folding {
	        nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space")<cr>
    	    vnoremap <Space> zf
	    " } // Toggle Folding

    	" Bubble match bracket {
	        nmap <C-up> [e
	        nmap <C-down> ]e
    	    vmap <C-up> [egv
	        vmap <C-down> ]egv
    	" } // Bubble match bracket

	    " Closing buffer {
			nmap <C-F4> :bdelete<cr>
            nmap <C-Left> :bprevious<cr>
            nmap <C-Right> :bnext<cr>
    	" } // Closing buffer

        " Pindah jendela {
            nmap <silent> <A-Up> :wincmd k<cr>
            nmap <silent> <A-Down> :wincmd j<cr>
            nmap <silent> <A-Left> :wincmd h<cr>
            nmap <silent> <A-Right> :wincmd l<cr>
        " } // Pindah cendela
    " } // Key mapping
" } // Config
